name: Example workflow using github context

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Print GitHub context
        run: echo "The event that triggered this workflow is ${{ github.event_name }}."
      - name: esta maniobra nos tomara 50 anios
        run: echo "${{ toJson(github) }}"
