name: hello-action

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: omenking/barsoom@0.0.6
        with:
          name: 'Brown'
      # Use the output from the `hello` step
      - name: Get the Output
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"
  my-push-info-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo body fields
        run: |
          echo "${{ toJson(github.event) }}"
          echo "${{ toJson(github.event) }}" | grep sender