name: inter-job-data-movement

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: MauroOyhanart/IntegratePrsDemo@c475da297b1cdb39aa653665e8360aae00d0688f
      with:
        prs: "1,2,3,433,89"
