name: inter-job-data-movement

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: MauroOyhanart/IntegratePrsDemo@8c22e9361e3e87440c64133eebd24026b9b0ffb9
      with:
        prs: ['hola', 'que tal']