name: inter-job-data-movement

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: MauroOyhanart/IntegratePrsDemo@26642ac9326e1702768af27719dbb5928634dd59
      with:
        prs: "1,2,3,4,89"
