name: Manual Trigger with Params

on:
  workflow_dispatch:
    inputs:
      prs:
        description: 'List of prs to approve'
        required: true
        type: string
      

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: testing
      uses: MauroOyhanart/IntegratePrsDemo@9380a5c0a20618ba7e79830ba6761d724a650b70
      with:
        prs: ${{ inputs.prs }}
