name: Manual Trigger with Params

on:
  workflow_dispatch:
    inputs:
      prs:
        description: 'List of prs to approve'
        required: true
        type: string
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: MauroOyhanart/IntegratePrsDemo@9360d15abfc7432c778036e915ef23dd2e57e8ea
      with:
        prs: ${{ inputs.prs }}
