name: Manual Trigger with Params

on:
  workflow_dispatch:
    inputs:
      prs:
        description: 'List of prs to approve'
        required: true
        type: string
      

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: testing
      uses: MauroOyhanart/IntegratePrsDemo@3ba2b3eb4912c82ebfd3bdd4c85f73869940db67
      with:
        prs: ${{ inputs.prs }}
